export enum UserEnum {
  BUYER = 'BUYER',
  SELLER = 'SELLER',
  MANAGER = 'MANAGER',
  ADMIN = 'ADMIN',
  DEALERSHIP_ADMIN = 'DEALERSHIP_ADMIN',
  DEALERSHIP_MANAGER = 'DEALERSHIP_MANAGER',
  DEALERSHIP_SELLER = 'DEALERSHIP_SELLER',
  DEALERSHIP_MECHANIC = 'DEALERSHIP_MECHANIC',
}
